🐰 Keploy: 2025-06-28T09:52:37+05:30 	[34mINFO[0m	Starting keploy in docker with image	{"image:": "ghcr.io/keploy/keploy:v2.6.14"}
🐰 Keploy: 2025-06-28T09:52:38+05:30 	[34mINFO[0m	Starting keploy in docker with default context, as that is the current context.
🐰 Keploy: 2025-06-28T09:52:38+05:30 	[31mERROR[0m	failed to list docker volumes	{"error": "error during connect: this error may indicate that the docker daemon is not running: Get \"http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/volumes?filters=%7B%22name%22%3A%7B%22debugfs%22%3Atrue%7D%7D\": open //./pipe/docker_engine: The system cannot find the file specified."}
🐰 Keploy: 2025-06-28T09:52:38+05:30 	[31mERROR[0m	failed to debugfs volume	{"error": "error during connect: this error may indicate that the docker daemon is not running: Get \"http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/volumes?filters=%7B%22name%22%3A%7B%22debugfs%22%3Atrue%7D%7D\": open //./pipe/docker_engine: The system cannot find the file specified."}
🐰 Keploy: 2025-06-28T09:52:38+05:30 	[31mERROR[0m	failed to run the command in docker	{"error": "error during connect: this error may indicate that the docker daemon is not running: Get \"http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/volumes?filters=%7B%22name%22%3A%7B%22debugfs%22%3Atrue%7D%7D\": open //./pipe/docker_engine: The system cannot find the file specified."}
🐰 Keploy: 2025-06-28T09:52:38+05:30 	[31mERROR[0m	failed to validate flags	{"error": "error during connect: this error may indicate that the docker daemon is not running: Get \"http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/volumes?filters=%7B%22name%22%3A%7B%22debugfs%22%3Atrue%7D%7D\": open //./pipe/docker_engine: The system cannot find the file specified."}
🐰 Keploy: 2025-06-28T09:52:38+05:30 	[31mERROR[0m	Error removing file	{"error": "remove keploy-logs.txt: The process cannot access the file because it is being used by another process."}
🐰 Keploy: 2025-06-28T09:52:38+05:30 	[31mERROR[0m	Failed to delete Keploy Logs	{"error": "remove keploy-logs.txt: The process cannot access the file because it is being used by another process."}
🐰 Keploy: 2025-06-28T09:53:28+05:30 	[34mINFO[0m	Starting keploy in docker with image	{"image:": "ghcr.io/keploy/keploy:v2.6.14"}
🐰 Keploy: 2025-06-28T09:53:28+05:30 	[34mINFO[0m	Starting keploy in docker with default context, as that is the current context.
🐰 Keploy: 2025-06-28T09:53:28+05:30 	[31mERROR[0m	failed to list docker volumes	{"error": "error during connect: this error may indicate that the docker daemon is not running: Get \"http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/volumes?filters=%7B%22name%22%3A%7B%22debugfs%22%3Atrue%7D%7D\": open //./pipe/docker_engine: The system cannot find the file specified."}
🐰 Keploy: 2025-06-28T09:53:28+05:30 	[31mERROR[0m	failed to debugfs volume	{"error": "error during connect: this error may indicate that the docker daemon is not running: Get \"http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/volumes?filters=%7B%22name%22%3A%7B%22debugfs%22%3Atrue%7D%7D\": open //./pipe/docker_engine: The system cannot find the file specified."}
🐰 Keploy: 2025-06-28T09:53:28+05:30 	[31mERROR[0m	failed to run the command in docker	{"error": "error during connect: this error may indicate that the docker daemon is not running: Get \"http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/volumes?filters=%7B%22name%22%3A%7B%22debugfs%22%3Atrue%7D%7D\": open //./pipe/docker_engine: The system cannot find the file specified."}
🐰 Keploy: 2025-06-28T09:53:28+05:30 	[31mERROR[0m	failed to validate flags	{"error": "error during connect: this error may indicate that the docker daemon is not running: Get \"http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/volumes?filters=%7B%22name%22%3A%7B%22debugfs%22%3Atrue%7D%7D\": open //./pipe/docker_engine: The system cannot find the file specified."}
🐰 Keploy: 2025-06-28T09:53:28+05:30 	[31mERROR[0m	Error removing file	{"error": "remove keploy-logs.txt: The process cannot access the file because it is being used by another process."}
🐰 Keploy: 2025-06-28T09:53:28+05:30 	[31mERROR[0m	Failed to delete Keploy Logs	{"error": "remove keploy-logs.txt: The process cannot access the file because it is being used by another process."}
🐰 Keploy: 2025-06-28T09:54:40+05:30 	[34mINFO[0m	Starting keploy in docker with image	{"image:": "ghcr.io/keploy/keploy:v2.6.14"}
🐰 Keploy: 2025-06-28T09:54:41+05:30 	[34mINFO[0m	Starting keploy in docker with default context, as that is the current context.
🐰 Keploy: 2025-06-28T09:54:41+05:30 	[31mERROR[0m	failed to list docker volumes	{"error": "error during connect: this error may indicate that the docker daemon is not running: Get \"http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/volumes?filters=%7B%22name%22%3A%7B%22debugfs%22%3Atrue%7D%7D\": open //./pipe/docker_engine: The system cannot find the file specified."}
🐰 Keploy: 2025-06-28T09:54:41+05:30 	[31mERROR[0m	failed to debugfs volume	{"error": "error during connect: this error may indicate that the docker daemon is not running: Get \"http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/volumes?filters=%7B%22name%22%3A%7B%22debugfs%22%3Atrue%7D%7D\": open //./pipe/docker_engine: The system cannot find the file specified."}
🐰 Keploy: 2025-06-28T09:54:41+05:30 	[31mERROR[0m	failed to run the command in docker	{"error": "error during connect: this error may indicate that the docker daemon is not running: Get \"http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/volumes?filters=%7B%22name%22%3A%7B%22debugfs%22%3Atrue%7D%7D\": open //./pipe/docker_engine: The system cannot find the file specified."}
🐰 Keploy: 2025-06-28T09:54:41+05:30 	[31mERROR[0m	failed to validate flags	{"error": "error during connect: this error may indicate that the docker daemon is not running: Get \"http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/volumes?filters=%7B%22name%22%3A%7B%22debugfs%22%3Atrue%7D%7D\": open //./pipe/docker_engine: The system cannot find the file specified."}
🐰 Keploy: 2025-06-28T09:54:41+05:30 	[31mERROR[0m	Error removing file	{"error": "remove keploy-logs.txt: The process cannot access the file because it is being used by another process."}
🐰 Keploy: 2025-06-28T09:54:41+05:30 	[31mERROR[0m	Failed to delete Keploy Logs	{"error": "remove keploy-logs.txt: The process cannot access the file because it is being used by another process."}
🐰 Keploy: 2025-06-28T09:56:24+05:30 	[34mINFO[0m	Starting keploy in docker with image	{"image:": "ghcr.io/keploy/keploy:v2.6.14"}
🐰 Keploy: 2025-06-28T09:56:24+05:30 	[34mINFO[0m	Starting keploy in docker with default context, as that is the current context.
🐰 Keploy: 2025-06-28T09:56:24+05:30 	[31mERROR[0m	failed to list docker volumes	{"error": "error during connect: this error may indicate that the docker daemon is not running: Get \"http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/volumes?filters=%7B%22name%22%3A%7B%22debugfs%22%3Atrue%7D%7D\": open //./pipe/docker_engine: The system cannot find the file specified."}
🐰 Keploy: 2025-06-28T09:56:24+05:30 	[31mERROR[0m	failed to debugfs volume	{"error": "error during connect: this error may indicate that the docker daemon is not running: Get \"http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/volumes?filters=%7B%22name%22%3A%7B%22debugfs%22%3Atrue%7D%7D\": open //./pipe/docker_engine: The system cannot find the file specified."}
🐰 Keploy: 2025-06-28T09:56:24+05:30 	[31mERROR[0m	failed to run the command in docker	{"error": "error during connect: this error may indicate that the docker daemon is not running: Get \"http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/volumes?filters=%7B%22name%22%3A%7B%22debugfs%22%3Atrue%7D%7D\": open //./pipe/docker_engine: The system cannot find the file specified."}
🐰 Keploy: 2025-06-28T09:56:24+05:30 	[31mERROR[0m	failed to validate flags	{"error": "error during connect: this error may indicate that the docker daemon is not running: Get \"http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/volumes?filters=%7B%22name%22%3A%7B%22debugfs%22%3Atrue%7D%7D\": open //./pipe/docker_engine: The system cannot find the file specified."}
🐰 Keploy: 2025-06-28T09:56:24+05:30 	[31mERROR[0m	Error removing file	{"error": "remove keploy-logs.txt: The process cannot access the file because it is being used by another process."}
🐰 Keploy: 2025-06-28T09:56:24+05:30 	[31mERROR[0m	Failed to delete Keploy Logs	{"error": "remove keploy-logs.txt: The process cannot access the file because it is being used by another process."}
